tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      rm -f awscliv2.zip
      cd $THEIA_WORKSPACE_ROOT
  - name: git
    init: |
      git config --global gpg.format ssh
      git config --global user.signingkey "$SSH_SIGNING_KEY"
      git config --global commit.gpgsign true
    command: bash
vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - ms-azuretools.vscode-docker