tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace
    init: |
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      rm -f awscliv2.zip
    command: |
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
  - name: aws-ssm
    before: |
      cd /workspace
    init: |
      curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
    command: |
      sudo dpkg -i session-manager-plugin.deb
      cd $THEIA_WORKSPACE_ROOT
  - name: postgres
    command: |
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
      sudo apt update
      sudo apt install -y postgresql-client-13 libpq-dev gettext-base
      export GITPOD_IP=$(curl ifconfig.me)
      source "$THEIA_WORKSPACE_ROOT/bin/rds/update-sg-rule"
  - name: flask
    command: |
      cd backend-flask
      pip install -r requirements.txt
  - name: git
    command: |
      git config --global gpg.format ssh
      git config --global user.signingkey "$SSH_SIGNING_KEY"
      git config --global commit.gpgsign true
vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - ms-azuretools.vscode-docker
    - ms-python.python
    - mtxr.sqltools
    - mtxr.sqltools-driver-pg
    - streetsidesoftware.code-spell-checker