AWSTemplateFormatVersion: 2010-09-09
Description: DNS configuration

Parameters:

  pDomainName:
    Description: A fully qualified domain name (e.g. domain.com)
    Type: String

Resources:

  rDomainHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref pDomainName
      HostedZoneConfig:
        Comment: !Sub '${pDomainName} public DNS zone'

  rCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      CertificateTransparencyLoggingPreference: ENABLED
      DomainName: !Sub '*.${pDomainName}'
      SubjectAlternativeNames:
        - !Ref pDomainName
      DomainValidationOptions:
        - DomainName: !Sub '*.${pDomainName}'
          HostedZoneId: !Ref rDomainHostedZone
      ValidationMethod: DNS

Outputs:

  oDomainHostedZoneId:
    Description: 'Hosted Zone ID'
    Value: !Ref rDomainHostedZone
    Export:
      Name: !Sub '${AWS::StackName}-HostedZoneId'

  oHostedZoneName:
    Description: 'Hosted Zone Name'
    Value: !Ref pDomainName
    Export:
      Name: !Sub '${AWS::StackName}-HostedZoneName'

  oDomainHostedZoneNameServers:
    Description: 'Hosted Zone Name Servers'
    Value: !Join [',', !GetAtt rDomainHostedZone.NameServers]

  oCertificateArn:
    Description: 'ACM Certificate ARN'
    Value: !Ref rCertificate
    Export:
      Name: !Sub '${AWS::StackName}-CertificateArn'
