version: 0.2

env:
  variables:
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - REPOSITORY_SERVER=$ECR_AWS_ACCOUNT_ID.dkr.ecr.$ECR_AWS_REGION.amazonaws.com
      - aws ecr get-login-password --region $ECR_AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_SERVER
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG -f "$CODEBUILD_SRC_DIR/backend-flask/Dockerfile.prod" --build-arg AWS_ACCOUNT_ID=$ECR_AWS_ACCOUNT_ID --build-arg ECR_AWS_REGION=$ECR_AWS_REGION --build-arg PYTHON_REPO_NAME=$PYTHON_REPO_NAME $CODEBUILD_SRC_DIR/backend-flask
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_SERVER/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_SERVER/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf "[{\"name\":\"$IMAGE_REPO_NAME\",\"imageUri\":\"$REPOSITORY_SERVER/$IMAGE_REPO_NAME:$IMAGE_TAG\"}]" > imagedefinitions.json

artifacts:
    files:
      - imagedefinitions.json